
spring:
  mail:
    host: smtp.gmail.com
    username: harshalhabib2002@gmail.com
    password: tqavjvwkmbtdrnks
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

